CREATE VIEW vw_DimProduct AS

SELECT [ProductKey]
      ,[SpanishProductSubcategoryName]
      ,[EnglishProductSubcategoryName]
      ,[SpanishProductCategoryName]
      ,[EnglishProductCategoryName]
      ,[EnglishProductName]
      ,[SpanishProductName]
      ,[FinishedGoodsFlag]
      ,[Color]
      ,[SafetyStockLevel]
      ,[ReorderPoint]
      ,[ListPrice]
      ,[DealerPrice]
      ,[StandardCost]
      ,[SizeUnitMeasureCode]
      ,[Size]
      ,[SizeRange]
      ,[WeightUnitMeasureCode]
      ,[Weight]
      ,[DaysToManufacture]
      ,[ModelName]
      ,[EnglishDescription]
      ,[StartDate]
      ,[EndDate]
      ,[Status]
  FROM [AdventureWorksDW2022].[dbo].[stg_Products]
